### PR TITLE
Update README.md

### LINKED ISSUE #7: README
Create and update README with architecture

### PR DESCRIPTION
**Pull request by dougsfelipe**

### CODE REVIEW

**Review by dougsfelipe — COMMENTED** [review]
Update Readme

**Comment by dougsfelipe** [comment]
Add images

**Review by JDaniielC — CHANGES_REQUESTED** [review]
Add images on README, maybe in README of frontend.

**Review by JDaniielC — CHANGES_REQUESTED** [review]
Add image architecture in README.

**Review by dougsfelipe — COMMENTED** [review]
Update documentation

**Pull request merged**
